# Generated by Django 3.2.5 on 2021-07-20 18:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(default=models.CharField(max_length=256))),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(default=models.CharField(max_length=250))),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sold_count', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='bag.jpg', null=True, upload_to='pictures/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('category', models.ForeignKey(default=app.models.get_default_category_id, on_delete=models.SET(app.models.get_defult_category), to='app.category')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
