# Generated by Django 3.2.5 on 2021-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='bag.jpg', null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
