# Generated by Django 3.2.5 on 2021-07-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_image'),
    ]

    operations = [
    ]
