# Generated by Django 3.2.5 on 2021-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210720_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
    ]
