# Generated by Django 3.2.5 on 2021-07-20 08:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caregory',
            field=models.ForeignKey(default='undefined', on_delete=models.SET(app.models.get_defult_category), to='app.category'),
        ),
    ]
